<?php
	$order = $block->getOrder();
?>

<div class="checkout-success">
	<?php if ($block->getOrderId()) : ?>
		<?php if ($order['state'] === 'pending_payment') : ?>
			<p><?= $block->escapeHtml(__('Your order will be processed once your payment has been confirmed')) ?></p>
		<?php endif; ?>
		<?php if ($block->getCanViewOrder()) : ?>
			<p><?= $block->escapeHtml(__('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeUrl($block->getViewOrderUrl()), $block->getOrderId())), ['a', 'strong']) ?></p>
		<?php else : ?>
			<p><?= $block->escapeHtml(__('Your order # is: <span>%1</span>.', $block->getOrderId()), ['span']) ?></p>
		<?php endif; ?>
	<?php endif; ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= $block->escapeUrl($block->getContinueUrl()) ?>"><span><?= $block->escapeHtml(__('Continue Shopping')) ?></span></a>
        </div>
    </div>
</div>
